version: "3.9"
services:
  seacap-ui:
    container_name: seacap-ui
    build:
      context: seacap-ui
    depends_on:
      - seacap-server
      - seacap-clusterer
  seacap-server:
    container_name: seacap-server
    build:
      context: seacap-server
  seacap-clusterer:
    container_name: seacap-clusterer
    build:
      context: seacap-clusterer
    environment:
      - FLASK_APP=app.py
