version: "3.9"
services: 
    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d:ro
        ports:
            - 5433:5432