FROM node:16 AS builder
WORKDIR /home/node/app
COPY . .
RUN [ "npm", "run", "build" ]

FROM nginx:1.21
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /home/node/app/dist/ /usr/share/nginx/html