FROM node:16 AS builder
WORKDIR /home/node/app
COPY . .
RUN [ "npm", "install" ]
RUN [ "npm", "run", "build" ]

FROM node:16-alpine3.11
USER node
WORKDIR /home/node/app
COPY --from=builder /home/node/app/ /home/node/app/
CMD [ "npm", "start" ]
